---
- hosts: all
  remote_user: will
  tasks:

    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest

    - name: install the latest version
      yum:
        name: telnet
        state: latest
    
    - name: install nginx
      yum:
        name: epel-release , nginx
        state: present
